# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trust_mediator.api.grpc import mediation_pb2 as mediation__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mediation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MediateContext = channel.unary_unary(
                '/trustmediator.v1.MediationService/MediateContext',
                request_serializer=mediation__pb2.ContextRequest.SerializeToString,
                response_deserializer=mediation__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.MediateToolCall = channel.unary_unary(
                '/trustmediator.v1.MediationService/MediateToolCall',
                request_serializer=mediation__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=mediation__pb2.ToolCallResponse.FromString,
                _registered_method=True)
        self.MediateMemoryWrite = channel.unary_unary(
                '/trustmediator.v1.MediationService/MediateMemoryWrite',
                request_serializer=mediation__pb2.MemoryWriteRequest.SerializeToString,
                response_deserializer=mediation__pb2.MemoryWriteResponse.FromString,
                _registered_method=True)
        self.MediateMemoryRead = channel.unary_unary(
                '/trustmediator.v1.MediationService/MediateMemoryRead',
                request_serializer=mediation__pb2.MemoryReadRequest.SerializeToString,
                response_deserializer=mediation__pb2.MemoryReadResponse.FromString,
                _registered_method=True)
        self.MediateOutput = channel.unary_unary(
                '/trustmediator.v1.MediationService/MediateOutput',
                request_serializer=mediation__pb2.OutputRequest.SerializeToString,
                response_deserializer=mediation__pb2.OutputResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/trustmediator.v1.MediationService/Health',
                request_serializer=mediation__pb2.HealthRequest.SerializeToString,
                response_deserializer=mediation__pb2.HealthResponse.FromString,
                _registered_method=True)


class MediationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def MediateContext(self, request, context):
        """POST /v1/mediate/context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediateToolCall(self, request, context):
        """POST /v1/mediate/tool-call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediateMemoryWrite(self, request, context):
        """POST /v1/mediate/memory/write
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediateMemoryRead(self, request, context):
        """POST /v1/mediate/memory/read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediateOutput(self, request, context):
        """POST /v1/mediate/output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """GET /health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MediateContext': grpc.unary_unary_rpc_method_handler(
                    servicer.MediateContext,
                    request_deserializer=mediation__pb2.ContextRequest.FromString,
                    response_serializer=mediation__pb2.ContextResponse.SerializeToString,
            ),
            'MediateToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.MediateToolCall,
                    request_deserializer=mediation__pb2.ToolCallRequest.FromString,
                    response_serializer=mediation__pb2.ToolCallResponse.SerializeToString,
            ),
            'MediateMemoryWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.MediateMemoryWrite,
                    request_deserializer=mediation__pb2.MemoryWriteRequest.FromString,
                    response_serializer=mediation__pb2.MemoryWriteResponse.SerializeToString,
            ),
            'MediateMemoryRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MediateMemoryRead,
                    request_deserializer=mediation__pb2.MemoryReadRequest.FromString,
                    response_serializer=mediation__pb2.MemoryReadResponse.SerializeToString,
            ),
            'MediateOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.MediateOutput,
                    request_deserializer=mediation__pb2.OutputRequest.FromString,
                    response_serializer=mediation__pb2.OutputResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mediation__pb2.HealthRequest.FromString,
                    response_serializer=mediation__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trustmediator.v1.MediationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trustmediator.v1.MediationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MediateContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trustmediator.v1.MediationService/MediateContext',
            mediation__pb2.ContextRequest.SerializeToString,
            mediation__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MediateToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trustmediator.v1.MediationService/MediateToolCall',
            mediation__pb2.ToolCallRequest.SerializeToString,
            mediation__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MediateMemoryWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trustmediator.v1.MediationService/MediateMemoryWrite',
            mediation__pb2.MemoryWriteRequest.SerializeToString,
            mediation__pb2.MemoryWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MediateMemoryRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trustmediator.v1.MediationService/MediateMemoryRead',
            mediation__pb2.MemoryReadRequest.SerializeToString,
            mediation__pb2.MemoryReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MediateOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trustmediator.v1.MediationService/MediateOutput',
            mediation__pb2.OutputRequest.SerializeToString,
            mediation__pb2.OutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trustmediator.v1.MediationService/Health',
            mediation__pb2.HealthRequest.SerializeToString,
            mediation__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
