apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trust-mediator
  namespace: trust-mediator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trust-mediator
